### ISSUE TITLE
Errors with screengrabs

### ISSUE THREAD

**Issue by supersammy7000** [tylerjaywood/pleasetakecareofmyplant#1]
1. 2016-06-23 11_57_31.482370-07_00_screengrab.jpg 
2. 2016-06-23 13_07_58.112890-07_00_screengrab.jpg
3. time_stamp_screengrab.jpg

Theses are the three images I can't open. I don't know if it is just me or if these files are corrupted or something. I have downloaded and extracted the zip download.

**Comment by supersammy7000** [comment]
I have looked at the files and they are just bad requests.

`<html>`
`<head><title>400 Bad Request</title></head>`
`<body bgcolor="white">`
`<center><h1>400 Bad Request</h1></center>`
`<hr><center>nginx</center>`
`</body>`
`</html>`

**Comment by t-jayw** [comment]
Deleted the bum screengrabs
